midi_note_dict = {
    "C0": 0,
    "C#0": 1,
    "D0": 2,
    "D#0": 3,
    "E0": 4,
    "F0": 5,
    "F#0": 6,
    "G0": 7,
    "G#0": 8,
    "A0": 9,
    "A#0": 10,
    "B0": 11,
    "C1": 12,
    "C#1": 13,
    "D1": 14,
    "D#1": 15,
    "E1": 16,
    "F1": 17,
    "F#1": 18,
    "G1": 19,
    "G#1": 20,
    "A1": 21,
    "A#1": 22,
    "B1": 23,
    "C2": 24,
    "C#2": 25,
    "D2": 26,
    "D#2": 27,
    "E2": 28,
    "F2": 29,
    "F#2": 30,
    "G2": 31,
    "G#2": 32,
    "A2": 33,
    "A#2": 34,
    "B2": 35,
    "C3": 36,
    "C#3": 37,
    "D3": 38,
    "D#3": 39,
    "E3": 40,
    "F3": 41,
    "F#3": 42,
    "G3": 43,
    "G#3": 44,
    "A3": 45,
    "A#3": 46,
    "B3": 47,
    "C4": 48,
    "C#4": 49,
    "D4": 50,
    "D#4": 51,
    "E4": 52,
    "F4": 53,
    "F#4": 54,
    "G4": 55,
    "G#4": 56,
    "A4": 57,
    "A#4": 58,
    "B4": 59,
    "C5": 60,
    "C#5": 61,
    "D5": 62,
    "D#5": 63,
    "E5": 64,
    "F5": 65,
    "F#5": 66,
    "G5": 67,
    "G#5": 68,
    "A5": 69,
    "A#5": 70,
    "B5": 71,
    "C6": 72,
    "C#6": 73,
    "D6": 74,
    "D#6": 75,
    "E6": 76,
    "F6": 77,
    "F#6": 78,
    "G6": 79,
    "G#6": 80,
    "A6": 81,
    "A#6": 82,
    "B6": 83,
    "C7": 84,
    "C#7": 85,
    "D7": 86,
    "D#7": 87,
    "E7": 88,
    "F7": 89,
    "F#7": 90,
    "G7": 91,
    "G#7": 92,
    "A7": 93,
    "A#7": 94,
    "B7": 95,
    "C8": 96,
    "C#8": 97,
    "D8": 98,
    "D#8": 99,
    "E8": 100,
    "F8": 101,
    "F#8": 102,
    "G8": 103,
    "G#8": 104,
    "A8": 105,
    "A#8": 106,
    "B8": 107,
    "C9": 108,
    "C#9": 109,
    "D9": 110,
    "D#9": 111,
    "E9": 112,
    "F9": 113,
    "F#9": 114,
    "G9": 115,
    "G#9": 116,
    "A9": 117,
    "A#9": 118,
    "B9": 119,
    "C10": 120,
    "C#10": 121,
    "D10": 122,
    "D#10": 123,
    "E10": 124,
    "F10": 125,
    "F#10": 126,
    "G10": 127
}
Q_BAR_OFFSET = (1/960)*1.3452465257518244e-42
beatmaking_percussion = [
  'hh',
  'hat',
  "kick",
  'drum',
  'snare',
  'tom',
  'counter snare',
  'countersnare',
  "snare drum",
  "hi hat",
  'hi-hat',
  "cymbal",
  "cymbal",
  "claps",
  'clap',
  "shaker",
  "tambourine",
  "claves",
  "cowbell",
  "congas",
  "bongos",
  "woodblock",
  "rimshot",
  'rim',
  "toms",
  'tom',
  "clap",
  "closed hi-hat",
"open hi-hat",
"sample",
"ride sample",
"laser shot",
"sweep",
  'cs',
  'snap',
  'hi hat',
  'percussions',
  'rim',
  'rim',
  'perc',
  'perc'
]
midi_map = [
    "Piano",
    'Harp',
    "Clavinet",
    'Clarinet',
    "Celesta",
    "Glockenspiel",
    "Music Box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Bells",
    'Bell',
    "Dulcimer",
    "Organ",
    "Accordion",
    "Harmonica",
    "Guitar",
    'Bass',
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Strings",
    "Timpani",
    'String',
    "Choir",
    "Voice",
    "Orchestra",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Horn",
    "Sax",
    'Synth',
    'Chord',
    "Oboe",
    "Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Blown Bottle",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Lead",
    "Pad",
    "FX",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bagpipe",
    "Fiddle",
    "Shanai",
    "Bell",
    "Agogo",
    "Drums",
    'Drum',
    'Kick',
    'kck',
    '808',
    '909',
    "Woodblock",
    'Voice',
    'Vocal',
    'Vox',
    "Tom",
    "Cymbal",
    "Breath Noise",
    "Seashore",
    "Tweet",
    'Brass'
    "Ring",
    "clap",
    "Stick",
    "Snare",
    "Hi-Hat",
    'hat',
    "Cymbal",

    "Tambourine",
    "Cowbell",
    "Vibraslap",
    "Bongo",
    "Conga",
    "Timbale",
    "Agogo",
    "Cabasa",
    "Maracas",
    "Whistle",
    "Guiro",
    "Claves",
    "Cuica",
    "Triangle",
    'rim',
    'arp',
    'perc',
    'snap',
    'melodies',
    'keys',
    'crash',
    'Crash',
    'hh',
    'percussion',
]

# Create a dictionary with instrument names as keys and MIDI program numbers as values
midi_dict = {
    "Acoustic Grand": 1,
    "Bright Acoustic": 2,
    "Electric Grand": 3,
    "Honky-Tonk": 4,
    "Electric Piano 1": 5,
    "Electric Piano 2": 6,
    "Harpsichord": 7,
    "Clav": 8,
    "Celesta": 9,
    "Glockenspiel": 10,
    "Music Box": 11,
    "Vibraphone": 12,
    "Marimba": 13,
    "Xylophone": 14,
    "Tubular Bells": 15,
    "Dulcimer": 16,
    "Drawbar Organ": 17,
    "Percussive Organ": 18,
    "Rock Organ": 19,
    "Church Organ": 20,
    "Reed Organ": 21,
    "Accordion": 22,
    "Harmonica": 23,
    "Tango Accordion": 24,
    "Acoustic Guitar (nylon)": 25,
    "Acoustic Guitar (steel)": 26,
    "Electric Guitar (jazz)": 27,
    "Electric Guitar (clean)": 28,
    "Electric Guitar (muted)": 29,
    "Overdriven Guitar": 30,
    "Distortion Guitar": 31,
    "Guitar Harmonics": 32,
    "Acoustic Bass": 33,
    "Electric Bass (finger)": 34,
    "Electric Bass (pick)": 35,
    "Fretless Bass": 36,
    "Slap Bass 1": 37,
    "Slap Bass 2": 38,
    "Synth Bass 1": 39,
    "Synth Bass 2": 40,
    "Violin": 41,
    "Viola": 42,
    "Cello": 43,
    "Contrabass": 44,
    "Tremolo Strings": 45,
    "Pizzicato Strings": 46,
    "Orchestral Strings": 47,
    "Timpani": 48,
    "String Ensemble 1": 49,
    "String Ensemble 2": 50,
    "SynthStrings 1": 51,
    "SynthStrings 2": 52,
    "Choir Aahs": 53,
    "Voice Oohs": 54,
    "Synth Voice": 55,
    "Orchestra Hit": 56,
    "Trumpet": 57,
    "Trombone": 58,
    "Tuba": 59,
    "Muted Trumpet": 60,
    "French Horn": 61,
    "Brass Section": 62,
    "SynthBrass 1": 63,
    "SynthBrass 2": 64,
    "Soprano Sax": 65,
    "Alto Sax": 66,
    "Tenor Sax": 67,
    "Baritone Sax": 68,
    "Oboe": 69,
    "English Horn": 70,
    "Bassoon": 71,
    "Clarinet": 72,
    "Piccolo": 73,
    "Flute": 74,
    "Recorder": 75,
    "Pan Flute": 76,
    "Blown Bottle": 77,
    "Shakuhachi": 78,
    "Whistle": 79,
    "Ocarina": 80,
    "Lead 1 (square)": 81,
    "Lead 2 (sawtooth)": 82,
    "Lead 3 (calliope)": 83,
    "Lead 4 (chiff)": 84,
    "Lead 5 (charang)": 85,
    "Lead 6 (voice)": 86,
    "Lead 7 (fifths)": 87,
    "Lead 8 (bass+lead)": 88,
    "Pad 1 (new age)": 89,
    "Pad 2 (warm)": 90,
    "Pad 3 (polysynth)": 91,
    "Pad 4 (choir)": 92,
    "Pad 5 (bowed)": 93,
    "Pad 6 (metallic)": 94,
    "Pad 7 (halo)": 95,
    "Pad 8 (sweep)": 96,
    "FX 1 (rain)": 97,
    "FX 2 (soundtrack)": 98,
    "FX 3 (crystal)": 99,
    "FX 4 (atmosphere)": 100,
    "FX 5 (brightness)": 101,
    "FX 6 (goblins)": 102,
    "FX 7 (echoes)": 103,
    "FX 8 (sci-fi)": 104,
    "Sitar": 105,
    "Banjo": 106,
    "Shamisen": 107,
    "Koto": 108,
    "Kalimba": 109,
    "Bagpipe": 110,
    "Fiddle": 111,
    "Shanai": 112,
    "Tinkle Bell": 113,
    "Agogo": 114,
    "Steel Drums": 115,
    "Woodblock": 116,
    "Taiko Drum": 117,
    "Melodic Tom": 118,
    "Synth Drum": 119,
    "Reverse Cymbal": 120,
    "Guitar Fret Noise": 121,
    "Breath Noise": 122,
    "Seashore": 123,
    "Bird Tweet": 124,
    "Telephone Ring": 125,
    "Helicopter": 126,
    "Applause": 127}

# Add percussions with a tuple (10, note of percussion)
percussion_dict = {
    "Acoustic Bass Drum": (10, 35),
    "Bass Drum 1": (10, 36),
    "Side Stick": (10, 37),
    "Acoustic Snare": (10, 38),
    "Hand Clap": (10, 39),
    "Electric Snare": (10, 40),
    "Low Floor Tom": (10, 41),
    "Closed Hi-Hat": (10, 42),
    "High Floor Tom": (10, 43),
    "Pedal Hi-Hat": (10, 44),
    "Low Tom": (10, 45),
    "Open Hi-Hat": (10, 46),
    "Low-Mid Tom": (10, 47),
    "Hi-Mid Tom": (10, 48),
    "Crash Cymbal 1": (10, 49),
    "High Tom": (10, 50),
    "Ride Cymbal 1": (10, 51),
    "Chinese Cymbal": (10, 52),
    "Ride Bell": (10, 53),
    "Tambourine": (10, 54),
    "Splash Cymbal": (10, 55),
    "Cowbell": (10, 56),
    "Crash Cymbal 2": (10, 57),
    "Vibraslap": (10, 58),
    "Ride Cymbal 2": (10, 59),
    "Hi Bongo": (10, 60),
    "Low Bongo": (10, 61),
    "Mute Hi Conga": (10, 62),
    "Open Hi Conga": (10, 63),
    "Low Conga": (10, 64),
    "High Timbale": (10, 65),
    "Low Timbale": (10, 66),
    "High Agogo": (10, 67),
    "Low Agogo": (10, 68),
    "Cabasa": (10, 69),
    "Maracas": (10, 70),
    "Short Whistle": (10, 71),
    "Long Whistle": (10, 72),
    "Short Guiro": (10, 73),
    "Long Guiro": (10, 74),
    "Claves": (10, 75),
    "Hi Wood Block": (10, 76),
    "Low Wood Block": (10, 77),
    "Mute Cuica": (10, 78),
    "Open Cuica": (10, 79),
    "Mute Triangle": (10, 80),
    "Open Triangle": (10, 81),
}




# Combine both dictionaries into one
full_midi_dict = {**midi_dict, **percussion_dict}

instrument_dict = {
    "Piano": "Electric Piano 1",
    "Harp": "Harpsichord",
    "Clavinet": "Clarinet",
    "Clarinet": "Clarinet",
    "Celesta": "Celesta",
    "Glockenspiel": "Glockenspiel",
    "Music Box": "Music Box",
    "Vibraphone": "Vibraphone",
    "Marimba": "Marimba",
    "Xylophone": "Xylophone",
    "Bells": "Tubular Bells",
    "Bell": "Tubular Bells",
    "Dulcimer": "Dulcimer",
    "Organ": "Drawbar Organ",
    "Accordion": "Tango Accordian",
    "Harmonica": "Harmonica",
    "Guitar": "Acoustic Guitar (nylon)",
    "Bass": "Acoustic Bass",
    "Violin": "Violin",
    "Viola": "Viola",
    "Cello": "Cello",
    "Contrabass": "Contrabass",
    "Strings": "Tremolo Strings",
    "Timpani": "Timpani",
    "String": "Tremolo Strings",
    "Choir": "Choir Aahs",
    "Voice": "Voice Oohs",
    "Orchestra": "Orchestral Strings",
    "Trumpet": "Trumpet",
    "Trombone": "Trombone",
    "Tuba": "Tuba",
    "Horn": "French Horn",
    "Sax": "Soprano Sax",
    "Synth": "Synth Bass 1",
    "Chord": "Harpsichord",
    "Oboe": "Oboe",
    "Horn": "French Horn",
    "Bassoon": "Bassoon",
    "Piccolo": "Piccolo",
    "Flute": "Flute",
    "Recorder": "Recorder",
    "Blown Bottle": "Blown Bottle",
    "Shakuhachi": "Shakuhachi",
    "Whistle": "Whistle",
    "Ocarina": "Ocarina",
    "Lead": "Lead 1 (square)",
    "Pad": "Pad 1 (new age)",
    "FX": "FX 1 (rain)",
    "Sitar": "Sitar",
    "Banjo": "Banjo",
    "Shamisen": "Shamisen",
    "Koto": "Koto",
    "Kalimba": "Kalimba",
    "Bagpipe": "Bagpipe",
    "Fiddle": "Fiddle",
    "Shanai": "Shanai",
    "Bell": "Tubular Bells",
    "Agogo": "Agogo",
    "Drums": "Steel Drums",
    "Drum": "Steel Drums",
    "Kick": "Bass Drum 1",
    "Woodblock": "Woodblock",
    "Vocal": "Voice Oohs",
    "Vox": "Voice Oohs",
    "Tom": "High Tom",
    "Cymbal": "Reverse Cymbal",
    "Breath Noise": "Breath Noise",
    "Seashore": "Seashore",
    "Tweet": "Bird Tweet",
    "Brass": "Brass Section",
    "Ring": "Tremolo Strings",
    "clap": "Hand Clap",
    "Stick": "Side Stick",
    "Snare": "Electric Snare",
    "Hi-Hat": "Open Hi-Hat",
    "Hat": "Open Hi-Hat",
    "Cymbal": "Reverse Cymbal",
    "Tambourine": "Tambourine",
    "Cowbell": "Cowbell",
    "Vibraslap": "Vibraslap",
    "Bongo": "Hi Bongo",
    "Conga": "Open Hi Conga",
    "Timbale": "High Timbale",
    "Cabasa": "Cabasa",
    "Maracas": "Maracas",
    "Whistle": "Whistle",
    "Guiro": "Long Guiro",
    "Claves": "Claves",
    "Cuica": "Open Cuica",
    "Triangle": "Open Triangle",
    "Rim": "Marimba",
    "Arp": "Harpsichord",
    "Perc": "Percussive Organ",
    "Snap": "Hand Clap",
        "Clap": "Hand Clap",
    "Percussion": "Bass Drum 1n",
'Tom' : 'High Tom',
    "Melodies": "Electric Grand",
    "Keys": "Electric Grand",
    '808': 'Steel Drums',
    '909' : 'Steel Drums',
    'Fx' : 'FX 1 (rain)',
    'Kck' : 'Bass Drum 1',
    'crash' : 'Crash Cymbal 1',
    'Crash' : 'Crash Cymbal 1',
    'Hh': 'Closed Hi-Hat',
    'Rim' : 'Side Stick'
    
}

styles = {
    'Hip Hop': 'Hip Hop',
    'R&B': 'RnB',
    'Pop': 'Pop',
    'Trap': 'Trap',
    'Boom Bap': 'Boom Bap',
    'Pain': 'Pop',
    'House': 'House',
    'RnB': 'RnB',
    'Afrobeat': 'Afro',
    'Drill': 'Drill',
    'Deep House': 'House',
    'Detroit': 'Trap',
    '2000s': 'Pop',
    'Funk': 'Funk',
    'West Coast': 'Hip Hop',
    'Pop - House': 'Pop',
    'New Jazz': 'Jazz',
    'Brazilian Funk': 'Funk',
    'Afrobeat - Dancehall': 'Afro',
    'Hood Trap': 'Trap',
    'Phonk': 'Hip Hop',
    'K-Pop': 'Pop',
    'Reegaeton': 'Reggaeton',
    'Funk BR': 'Funk',
    'Afro': 'Afro',
    'Reggaeton': 'Reggaeton',
    'Reggae': 'Reggaeton',
    'Jazz': 'Jazz',
    'K-pop': 'Pop',
    'EDM': 'EDM',
    'Electronic': 'EDM',
    '90s': 'Pop',
    'Afrobeat': 'Afro',
    "Based on the file name 'Gimmie A Light.txt', the musical genre that might best describe its style could likely be Reggae.": 'Reggaeton',
    'Baton Rouge': 'Trap',
    'Brazilian Funk': 'Funk',
    'Cinematic': 'Cinematic',
    'Dembow': 'Reggaeton',
    'Digital - Rage': 'Electronic',
    'Drum & Bass': 'D&B',
    'Drum And Bass': 'D&B',
    'Drum and Bass': 'D&B',
    'Future Bass': 'EDM',
    'Glo': 'Hip Hop',
    'Grime': 'Hip Hop',
    'Hip Hop ': 'Hip Hop',
    'K-Pop': 'Pop',
    'New Jazz': 'Jazz',
    'Plug': 'Hip Hop',
    'Pluggnb': 'Hip Hop',
    'Trance': 'EDM',
    'UK Garage': 'Electronic',
    'Wavy': 'Electronic',
}

int_to_note = {0 : 'C', 1 : 'C#', 2 : 'D', 3 : 'D#', 4 : 'E', 5 : 'F', 6 : 'F#', 7 : 'G', 8 : 'G#', 9 : 'A', 10 : 'A#', 11 : 'B'}